// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static QRCodeManagement.Controllers.AccountController Account = new QRCodeManagement.Controllers.T4MVC_AccountController();
    public static QRCodeManagement.Controllers.CheckingController Checking = new QRCodeManagement.Controllers.T4MVC_CheckingController();
    public static QRCodeManagement.Controllers.ErrorController Error = new QRCodeManagement.Controllers.T4MVC_ErrorController();
    public static QRCodeManagement.Controllers.ManageUserController ManageUser = new QRCodeManagement.Controllers.T4MVC_ManageUserController();
    public static QRCodeManagement.Controllers.QrInfoController QrInfo = new QRCodeManagement.Controllers.T4MVC_QrInfoController();
    public static QRCodeManagement.Controllers.QrManagementController QrManagement = new QRCodeManagement.Controllers.T4MVC_QrManagementController();
    public static QRCodeManagement.Controllers.StaticticsController Statictics = new QRCodeManagement.Controllers.T4MVC_StaticticsController();
    public static QRCodeManagement.Controllers.SuccessController Success = new QRCodeManagement.Controllers.T4MVC_SuccessController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string ai_0_15_0_build58334_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/ai.0.15.0-build58334.min.js") ? Url("ai.0.15.0-build58334.min.js") : Url("ai.0.15.0-build58334.js");
        public static readonly string ai_0_15_0_build58334_min_js = Url("ai.0.15.0-build58334.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Applications {
            private const string URLPATH = "~/Scripts/Applications";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string App_Modal_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/App.Modal.min.js") ? Url("App.Modal.min.js") : Url("App.Modal.js");
            public static readonly string App_QR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/App.QR.min.js") ? Url("App.QR.min.js") : Url("App.QR.js");
        }
    
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Pages {
            private const string URLPATH = "~/Scripts/Pages";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string Page_Chart_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.Chart.min.js") ? Url("Page.Chart.min.js") : Url("Page.Chart.js");
            public static readonly string Page_CheckingQR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.CheckingQR.min.js") ? Url("Page.CheckingQR.min.js") : Url("Page.CheckingQR.js");
            public static readonly string Page_CreateQR_CreateFile_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.CreateQR.CreateFile.min.js") ? Url("Page.CreateQR.CreateFile.min.js") : Url("Page.CreateQR.CreateFile.js");
            public static readonly string Page_CreateQR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.CreateQR.min.js") ? Url("Page.CreateQR.min.js") : Url("Page.CreateQR.js");
            public static readonly string Page_CreateQR_RenderColorPicker_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.CreateQR.RenderColorPicker.min.js") ? Url("Page.CreateQR.RenderColorPicker.min.js") : Url("Page.CreateQR.RenderColorPicker.js");
            public static readonly string Page_CreateQR_VCardApp_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.CreateQR.VCardApp.min.js") ? Url("Page.CreateQR.VCardApp.min.js") : Url("Page.CreateQR.VCardApp.js");
            public static readonly string Page_Frame_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.Frame.min.js") ? Url("Page.Frame.min.js") : Url("Page.Frame.js");
            public static readonly string Page_Login_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.Login.min.js") ? Url("Page.Login.min.js") : Url("Page.Login.js");
            public static readonly string Page_Logo_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.Logo.min.js") ? Url("Page.Logo.min.js") : Url("Page.Logo.js");
            public static readonly string Page_ManageQR_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.ManageQR.min.js") ? Url("Page.ManageQR.min.js") : Url("Page.ManageQR.js");
            public static readonly string Page_Template_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.Template.min.js") ? Url("Page.Template.min.js") : Url("Page.Template.js");
            public static readonly string Page_UserManager_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Page.UserManager.min.js") ? Url("Page.UserManager.min.js") : Url("Page.UserManager.js");
        }
    
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        public static readonly string Loading_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Loading.min.css") ? Url("Loading.min.css") : Url("Loading.css");
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class Applications 
            {
                public static class Assets
                {
                    public const string App_Modal_js = "~/Scripts/Applications/App.Modal.js"; 
                    public const string App_QR_js = "~/Scripts/Applications/App.QR.js"; 
                }
            }
            public static partial class Pages 
            {
                public static class Assets
                {
                    public const string Page_Chart_js = "~/Scripts/Pages/Page.Chart.js"; 
                    public const string Page_CheckingQR_js = "~/Scripts/Pages/Page.CheckingQR.js"; 
                    public const string Page_CreateQR_CreateFile_js = "~/Scripts/Pages/Page.CreateQR.CreateFile.js"; 
                    public const string Page_CreateQR_js = "~/Scripts/Pages/Page.CreateQR.js"; 
                    public const string Page_CreateQR_RenderColorPicker_js = "~/Scripts/Pages/Page.CreateQR.RenderColorPicker.js"; 
                    public const string Page_CreateQR_VCardApp_js = "~/Scripts/Pages/Page.CreateQR.VCardApp.js"; 
                    public const string Page_Frame_js = "~/Scripts/Pages/Page.Frame.js"; 
                    public const string Page_Login_js = "~/Scripts/Pages/Page.Login.js"; 
                    public const string Page_Logo_js = "~/Scripts/Pages/Page.Logo.js"; 
                    public const string Page_ManageQR_js = "~/Scripts/Pages/Page.ManageQR.js"; 
                    public const string Page_Template_js = "~/Scripts/Pages/Page.Template.js"; 
                    public const string Page_UserManager_js = "~/Scripts/Pages/Page.UserManager.js"; 
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string ai_0_15_0_build58334_js = "~/Scripts/ai.0.15.0-build58334.js"; 
                public const string ai_0_15_0_build58334_min_js = "~/Scripts/ai.0.15.0-build58334.min.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_1_10_2_intellisense_js = "~/Scripts/jquery-1.10.2.intellisense.js"; 
                public const string jquery_1_10_2_js = "~/Scripts/jquery-1.10.2.js"; 
                public const string jquery_1_10_2_min_js = "~/Scripts/jquery-1.10.2.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string Loading_css = "~/Content/Loading.css";
                public const string Site_css = "~/Content/Site.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


